### ISSUE TITLE
Standardize error handing

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Java-SDK#55]
here needs to be a set of Error types defined and their meaning nailed down so that developers can predictably deal with error conditions.

This will also be subject to an internal API Review.

**Comment by davideberlein** [comment]
The Error handling at the moment is a big problem for us.
When calling 
```
OpenTok openTok = new OpenTok(getApiKey(), getApiSecret());
openTok.createSession(new SessionProperties.Builder().mediaMode(mode).build());
``` 
with invalid / licence time out API Key I will simply get a ResourceException with the message: `Could not create an OpenTok Session. The server response was invalid. response code: 403`

This sort of Error is absolutely un-handable for us since we can't determine what the exact error is and therefore can't react correctly.
Adding the response Object into the Exception would be a good first step for us. A standardised error handling would be better but we need a fast solution.

Best Regards 

David

**Comment by aoberoi** [comment]
thanks @davideberlein. i think this issue has been around too long and we need to get moving on it. its actually affecting the other server language SDKs as well, so its sort of a larger effort than one might initially think. i believe i'll be about to find the resources to work on this in the next few weeks.
