### ISSUE TITLE
Can't use sdk

### ISSUE THREAD

**Issue by mikebell90** [opentok/Opentok-Java-SDK#79]
Created a simple maven projection, only dependency is 2.3.1 tokbox

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>speakeasy</groupId>
  <artifactId>testtokbox</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>tokboxtest</name>
  <dependencies>
  <dependency>
    <groupId>com.tokbox</groupId>
    <artifactId>opentok-server-sdk</artifactId>
    <version>2.3.1</version>
  </dependency>
  </dependencies>
</project>

Wrote a simple bit of code to initialize tokbox, and then generate tokens and sessinos

and get

Exception in thread "main" java.lang.NoSuchMethodError: com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.setParameters(Lcom/ning/http/client/FluentStringsMap;)Lcom/ning/http/client/AsyncHttpClient$BoundRequestBuilder;
	at com.opentok.util.HttpClient.createSession(HttpClient.java:48)
	at com.opentok.OpenTok.createSession(OpenTok.java:252)
	at TokBoxUtil.createSession(TokBoxUtil.java:24)
	at TokBoxUtil.main(TokBoxUtil.java:46)

**Comment by mikebell90** [comment]
This ends up loading async client 1.9.x which is still not compatible with the publishd 2.3.1 ?

**Comment by mikebell90** [comment]
A forced import of 1.8.16 worked.

**Comment by aoberoi** [comment]
thanks @mikebell90 for debugging the issue and for updating the ticket.

this is related to #75. its clear that the version specifier needs to be updated, but the question is whether picking something that is 1.8.x or 1.9.x is better. obviously for new projects, 1.9.x makes sense. i'm trying to gather a general sense of if users of this library have other dependencies which actually require 1.8.x so this would cause conflicts. i'm starting to lean towards 1.9.x so that we can at least accommodate new users well and users who have issues will start speaking up. do you have any opinions?

**Comment by mikebell90** [comment]
Use 1.9. 
Use a specific version not a range. Leave it to people subsuming in other projects to change that IMO.
