### ISSUE TITLE
Underlying async-http-client resources are not released when an OpenTok instance is discared

### ISSUE THREAD

**Issue by massimoscorletti** [opentok/Opentok-Java-SDK#84]
There is no way to "close" an OpenTok object in order to properly release resources (i.e. threads) allocated by the AsyncHttpClient.

**Comment by aoberoi** [comment]
@massimoscorletti thanks for filing the issue. i just want to learn a little more about your concern. the AsyncHttpClient instance will by default maintain a connection pool. afaik, there is a maximum time to keep the connection in the pool, and after that the resources would automatically be released. if you have observed some other behavior, or are talking about a different problem, that would be good to know.

see: https://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/AsyncHttpClientConfig.html#getIdleConnectionInPoolTimeoutInMs()

**Comment by massimoscorletti** [comment]
The point is: when you discard an OpenTok object the unedrlying AsyncHttpClient is not closed, and the resources allocated by the pool are not released.

I have a long running application with multiple OpenTok objects (different api keys).
Each OpenTok instance is cached and reused for a period, than discarded.
In this situation i have more and more threads allocated by "phantom" AsyncHttpClient instances.

To avoid this problem I've subclassed the OpenTok class by adding a close() method with a call to [http://static.javadoc.io/com.ning/async-http-client/1.9.33/com/ning/http/client/AsyncHttpClient.html#closeAsynchronously--
]

**Comment by aoberoi** [comment]
@massimoscorletti by default, there is an idle timeout for the connections in the connection pool, and the value is 60 seconds. are you saying that value is not good for your application? are you saying you want to configure this value? or, are you saying that you'd prefer to explicitly dispose of those resources even knowing that after 60 seconds the resources would be freed?

**Comment by massimoscorletti** [comment]
I'm not talking about connections, I'm talking about threads.
For every OpenTok instance, a new thread pool is spawned, and it seems to me that those threads are never closed.

**Comment by aoberoi** [comment]
Thanks for clearing that up. I was able to reproduce the behavior you are noting. Specifically, there are a number of I/O Worker threads, at least one I/O Boss thread, and a Hashed Timer thread that stick around for each OpenTok instance you use. Those threads don't seem to die even after you explicitly remove all references to the OpenTok instance, and wait for the 60 second idle time.

From my reading of the documentation, I think this is unexpected behavior. I've done some digging in the code of AHC myself to figure out if there was some configuration I could set to obtain the behavior I desire. I'm a little bit out of my depths so I left this post on the project's mailing list: https://groups.google.com/forum/#!searchin/asynchttpclient/worker/asynchttpclient/iuoYliJBfBg/JcmL0mhrBDAJ

In general, I'm really glad you brought this issue up. If it comes down to it, I'm not opposed to adding a `.close()` method to the OpenTok instance, but I'd like to avoid it if possible. Also, I realized that since thread pools are a valuable resource for programs using this library, it might actually make sense to expose a `.setExecutorService()` method on the OpenTok instance (or its Builder) so that programs can be optimized to reuse an existing thread pool instead of dealing with a brand new one.

**Comment by aoberoi** [comment]
@massimoscorletti based on the feedback from the mailing list, here is my proposal for changes:

```
public class OpenTok implements Closable {
  //...
  protected void finalize() throws Throwable;
  public void close() throws IOException;
  public boolean isClosed();
}
```

in addition, all methods that potentially call the AHC instance will need to also throw `IOException`. Right now we wrap (not really, just swallow and then re-throw) these exceptions with `OpenTokException` subclass instances, but in order to be a good citizen, we should throw the `IOException`.

**Comment by massimoscorletti** [comment]
Thank you for your reply.

Just a comment on the hypothetical .setExecutorService() method: very good idea, but please note that it would be useful to configure different aspects of the underlying AHC client, such as timeouts, proxy support, etc (I've filed another issue for proxy support).

What about giving the caller the ability to inject its own AsyncHttpClientConfig object (maybe using a "proxy" configuration bean)?

**Comment by aiham** [comment]
FYI we've added a close method. See #121
